### PR TITLE
fix: media upload to have applicationName as User-Agent

### LINKED ISSUE #2222: AbstractGoogleClientRequest.initializeMediaUpload is not using applicationName to User-Agent HTTP header
Internal bug b/252963877. mediaHttpUploader is not adding a proper User-Agent HTTP header.

```
        String userAgent = "Foo/1.0";
        Storage storage = new Storage.Builder(rf.getTransport(), jsonFactory, rf.getInitializer())
            .setApplicationName(userAgent)
            .build();
...
        Insert insert = storage.objects().insert(bucket, storageObject, content);
        GenericUrl url = insert.buildHttpRequestUrl();
        MediaHttpUploader mediaHttpUploader = insert.getMediaHttpUploader();

        // This does not add the expected user-agent header to the request.
        HttpResponse upload = mediaHttpUploader.upload(url);
```

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4.  version(s):

The `com.google.apis:google-api-services-storage:v1-rev20220705-2.0.0` and `google-api-client:2.0.0`.

#### Steps to reproduce

Declare dependencies:

```
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-storage</artifactId>
      <version>v1-rev20220705-2.0.0</version>
    </dependency>
```

#### Code example

```java
    // Run with VM option to have -Djava.util.logging.config.file=src/main/resources/logging.properties
    public static void main( String[] args ) throws Exception {
        NetHttpTransport transport = new NetHttpTransport.Builder()
            .trustCertificates(GoogleUtils.getCertificateTrustStore())
            .build();
        HttpRequestFactory rf = transport.createRequestFactory();
        JsonFactory jsonFactory = new GsonFactory();

        String userAgent = "Foo/1.0";
        Storage storage = new Storage.Builder(rf.getTransport(), jsonFactory, rf.getInitializer())
            .setApplicationName(userAgent)
            .build();


        // Project suztomo-terraform-4f9e48 has this bucket.
        String bucket = "suztomo_test_b252963877"; // TODO: replace with your bucket

        StorageObject storageObject = new StorageObject().setName("temp.txt").setBucket(bucket);
        byte[] bytes = "hi".getBytes(StandardCharsets.UTF_8);
        ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
        InputStreamContent content = new InputStreamContent("text/plain", bais);

        Insert insert = storage.objects().insert(bucket, storageObject, content);
        GenericUrl url = insert.buildHttpRequestUrl();
        MediaHttpUploader mediaHttpUploader = insert.getMediaHttpUploader();

        // This does not add the expected user-agent header to the request.
        HttpResponse upload = mediaHttpUploader.upload(url);
        System.out.println("Upload response code: " + upload.getStatusCode() + " " + upload.getStatusMessage());
    }
```

This does not send the user agent to the server.

#### External references such as API reference guides

- ?

#### Any additional information below

Internal bug b/252963877.

Setting request initializer as the 3rd argument to `Storage.Builder` is the workaround:

```
        HttpCredentialsAdapter credentialsInitializer = new HttpCredentialsAdapter(credentials);
        HttpRequestInitializer requestInitializer = new HttpRequestInitializer() {
            @Override
            public void initialize(HttpRequest request) throws IOException {
                credentialsInitializer.initialize(request);
                HttpHeaders headers = request.getHeaders();
                headers.setUserAgent(userAgent);
            }
        };

...(omit)...

        Storage storage = new Storage.Builder(rf.getTransport(), jsonFactory, requestInitializer)
            .setApplicationName(userAgent)
            .build();
```

But the library users shouldn't need to do that.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #2222 

- Upload to have applicationName as User-Agent
- request initializer to set user-agent header

How I confirmed the fix:

I locally installed this branch via `mvn install` and specified the SNAPSHOT version of the BOM:

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.api-client</groupId>
        <artifactId>google-api-client-bom</artifactId>
        <version>2.1.3-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-storage</artifactId>
      <version>v1-rev20220705-2.0.0</version>
    </dependency>
...
```

I ran @BenWhitehead 's reproducer (with my small modification):

```java
package org.example;

import static sun.net.www.protocol.http.HttpURLConnection.userAgent;

import com.google.api.client.googleapis.GoogleUtils;
import com.google.api.client.googleapis.media.MediaHttpUploader;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpHeaders;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpRequestFactory;
import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.InputStreamContent;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.gson.GsonFactory;
import com.google.api.services.storage.Storage;
import com.google.api.services.storage.Storage.Objects.Insert;
import com.google.api.services.storage.model.StorageObject;
import com.google.auth.http.HttpCredentialsAdapter;
import com.google.auth.oauth2.GoogleCredentials;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;

public class App 
{
    // Run with VM option to have -Djava.util.logging.config.file=src/main/resources/logging.properties
    public static void main( String[] args ) throws Exception {
        GoogleCredentials credentials = GoogleCredentials.getApplicationDefault();
        String userAgent = "Foo/1.0 (Bar:Baz/1.0) Tomo/1.0";
        HttpCredentialsAdapter credentialsInitializer = new HttpCredentialsAdapter(credentials);

        NetHttpTransport transport = new NetHttpTransport.Builder()
            .trustCertificates(GoogleUtils.getCertificateTrustStore())
            .build();
        HttpRequestFactory rf = transport.createRequestFactory();
        JsonFactory jsonFactory = new GsonFactory();

        Storage storage = new Storage.Builder(rf.getTransport(), jsonFactory, credentialsInitializer)
            .setApplicationName(userAgent)
            .build();


        // Project suztomo-terraform-4f9e48 has this bucket.
        String bucket = "suztomo_test_b252963877"; // TODO: replace with your bucket

        StorageObject storageObject = new StorageObject().setName("temp.txt").setBucket(bucket);
        byte[] bytes = "hi".getBytes(StandardCharsets.UTF_8);
        ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
        InputStreamContent content = new InputStreamContent("text/plain", bais);

        Insert insert = storage.objects().insert(bucket, storageObject, content);
        GenericUrl url = insert.buildHttpRequestUrl();
        MediaHttpUploader mediaHttpUploader = insert.getMediaHttpUploader();

        HttpResponse upload = mediaHttpUploader.upload(url);
        System.out.println("Upload response code: " + upload.getStatusCode() + " " + upload.getStatusMessage());
    }
}
```

 Note that userAgent is used in only `setApplicationName(userAgent)`.

I placed src/main/resources/logging.properties so that it prints debug (FINE-level) log:

```
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = FINE

# Set up logging of HTTP requests and responses (uncomment "level" to show)
com.google.api.level = FINE
```

This is specified via `-Djava.util.logging.config.file=src/main/resources/logging.properties` argument in IntelliJ.

It printed out the expected User-Agent when uploading the data:

```
...
Jan 20, 2023 10:59:01 AM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
PUT https://storage.googleapis.com/upload/storage/v1/b/suztomo_test_b252963877/o?uploadType=resumable&upload_id=ADPycdstG5t6ppvQpO9MoZROy-k67Qonkt_EFy8fUv5NQOW6hODYzBs8T3iEBy3UD9qy4xz25pnrOc41j_te7WPdu4ZG
Accept-Encoding: gzip
Authorization: <Not Logged>
Content-Range: bytes 0-1/2
User-Agent: Foo/1.0 (Bar:Baz/1.0) Tomo/1.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-user-project: suztomo-terraform-4f9e48
...
```

### CODE REVIEW

**Comment by lqiu96** [comment]
LGTM -- Changes make sense. I do that the `setApplicationName` -> User Agent header is documented here: https://github.com/googleapis/google-api-java-client/blob/0d1e5dbf37dd45d6cb40abec72ae43eaa1dd1863/google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java#L453-L463 inside `AbstractGoogleClient`. I think this is searchable on CloudRAD, but is hidden away in the Builder: https://cloud.google.com/java/docs/reference/google-api-client/latest/com.google.api.client.googleapis.services.AbstractGoogleClient.Builder#com_google_api_client_googleapis_services_AbstractGoogleClient_Builder_setApplicationName_java_lang_String_

Do you think it would make sense to have this documented a bit more visible?

**Comment by suztomo** [comment]
> is hidden away in the Builder

I see it in IntelliJ. Where do you wish you want to see it?

Screenshot 2023-01-20 at 11 45 23 AM

**Review by lqiu96 — APPROVED** [review]

File: google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java [hunk 1]
```diff
@@ -351,15 +351,42 @@ public final MediaHttpUploader getMediaHttpUploader() {
    */
   protected final void initializeMediaUpload(AbstractInputStreamContent mediaContent) {
     HttpRequestFactory requestFactory = abstractGoogleClient.getRequestFactory();
+    String applicationName = abstractGoogleClient.getApplicationName();
+    HttpRequestInitializer requestInitializer =
+        mediaUploadRequestUserAgentInitializer(applicationName, requestFactory.getInitializer());
     this.uploader =
```
Comment (suztomo) [inline google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java:357]: Special handling for `applicationName`,
Screenshot 2023-01-20 at 9 49 39 AM

**Comment by suztomo** [comment]
@BenWhitehead Would you review this fix? The pull request description has how I confirmed it with regard to the internal bug b/252963877.

**Review by BenWhitehead — APPROVED** [review]
