### PR TITLE
Fix Copyright notices

### LINKED ISSUE #1168: Bad Copyright Notices
Some files have a copyright notice like this:

Copyright (c) 2013 Google Inc.

This is incorrect under the law. (c) is meaningless. The word Copyright is sufficient. New files should have 

Copyright 2018 Google LLC.

though we don't have to change Inc. to LLC where it's otherwise fine.

### PR DESCRIPTION
**Pull request by elharo**
@chingor13 fix #1168

### CODE REVIEW

File: google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/accounts/GoogleAccountManager.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2012 Google Inc.
+ * Copyright 2012 Google Inc.
```
Comment (chingor13) [inline google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/accounts/GoogleAccountManager.java]: Should they be `Google LLC` too?

Comment (elharo) [reply google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/accounts/GoogleAccountManager.java]: I asked the internal copyright folks about this a few months back in another project. They told me not to bother changing that, but new files should be LLC.
