### PR TITLE
fix: user-agent should use identifier/version

### LINKED ISSUE #1426: User-Agent string uses invalid format
The default user agent (and appended user agent) only uses `Google-API-Java-Client`. It should include the version (e.g. `Google-API-Java-Client/1.30.6`)

This blocks reporting on the backend with regards to which version of the google-api-client is being used.

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #1426

### CODE REVIEW

File: google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java [hunk 1]
```diff
@@ -203,7 +204,7 @@ public void testUserAgentSuffix() throws Exception {
     // Specify an Application Name.
     String applicationName = "Test Application";
     transport.expectedUserAgent = applicationName + " "
```
Comment (elharo) [inline google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java]: You can inline AbstractGoogleClientRequest.USER_AGENT_SUFFIX  and applicationName here and the test becomes a little stronger since it's no longer duplicating as much of the logic in the model code.

Comment (chingor13) [reply google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java]: That constant is public, so I'm not sure if that would possibly break users.

Comment (chingor13) [reply google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java]: Oh, misread the comment. I'll update that.

Comment (elharo) [reply google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java]: Using a string literal instead of a constant tests the constant. Using the constant simply guarantees that any mistakes in the constant value will not be caught by the tests. Yes, I've seen constants with bugs in them. :-(

Comment (chingor13) [reply google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java]: Done.
